@{
    'EdgeStable.WebDataPath' = "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\Web Data"
    'EdgeDev.WebDataPath' = "$env:LOCALAPPDATA\Microsoft\Edge Dev\User Data\Default\Web Data"
    'EdgeBeta.WebDataPath' = "$env:LOCALAPPDATA\Microsoft\Edge Beta\User Data\Default\Web Data"
    'EdgeCanary.WebDataPath' = "$env:LOCALAPPDATA\Microsoft\Edge SxS\User Data\Default\Web Data"
    'EdgeStable.CopyToPath' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeStable\\WebData.SQLite"
    'EdgeDev.CopyToPath' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeDev\\WebData.SQLite"
    'EdgeBeta.CopyToPath' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeBeta\\WebData.SQLite"
    'EdgeCanary.CopyToPath' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeCanary\\WebData.SQLite"
    'EdgeStable.OutputPath' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeStable"
    'EdgeDev.OutputPath' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeDev"
    'EdgeBeta.OutputPath' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeBeta"
    'EdgeCanary.OutputPath' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeCanary"
    'EdgeStable.OutputCSVFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeStable\\Keywords.csv"
    'EdgeDev.OutputCSVFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeDev\\Keywords.csv"
    'EdgeBeta.OutputCSVFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeBeta\\Keywords.csv"
    'EdgeCanary.OutputCSVFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeCanary\\Keywords.csv"
    'EdgeStable.OutputJSONFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeStable\\Keywords.json"
    'EdgeDev.OutputJSONFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeDev\\Keywords.json"
    'EdgeBeta.OutputJSONFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeBeta\\Keywords.json"
    'EdgeCanary.OutputJSONFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeCanary\\Keywords.json"
    'EdgeStable.OutputSQLFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeStable\\Keywords.sql"
    'EdgeDev.OutputSQLFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeDev\\Keywords.sql"
    'EdgeBeta.OutputSQLFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeBeta\\Keywords.sql"
    'EdgeCanary.OutputSQLFile' = "$env:AppData\\PowerShell\\PSEdgeKeyWords\\EdgeCanary\\Keywords.sql"
    'SQLExportScriptPath' = "$env:USERPROFILE\\Documents\\PowerShell\\Modules\\PSEdgeKeywords\\*\\SQL\\ExportEdgeKeywords.sql"
    'SQLImportScriptPath' = "$env:USERPROFILE\\Documents\\PowerShell\\Modules\\PSEdgeKeywords\\*\\SQL\\ImportEdgeKeywords.sql"
}
