name: Build Module
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitVersion
        id: gitversion
        uses: PoshCode/Actions/gitversion@v1
      - name: Install-RequiredModules
        uses: PoshCode/Actions/install-requiredmodules@v1
      - name: Build Module
        id: build
        uses: PoshCode/actions/build-module@v1
        with:
          version: ${{ steps.gitversion.outputs.LegacySemVerPadded }}
          destination: ${{github.workspace}}/Output
      - name: Upload Build Output
        uses: actions/upload-artifact@v2
        with:
          name: Modules
          path: ${{github.workspace}}/Output
      - name: Upload Tests
        uses: actions/upload-artifact@v2
        with:
          name: PesterTests
          path: ${{github.workspace}}/tests
      - name: Upload RequiredModules.psd1
        uses: actions/upload-artifact@v2
        with:
          name: RequiredModules
          path: ${{github.workspace}}/RequiredModules.psd1
      - name: Upload PSScriptAnalyzerSettings.psd1
        uses: actions/upload-artifact@v2
        with:
          name: ScriptAnalyzer
          path: ${{github.workspace}}/PSScriptAnalyzerSettings.psd1
      - name: Publish Test Results
        uses: zyborg/dotnet-tests-report@v1
        with:
          test_results_path: ./tests/out/testResults.xml
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: ./tests/out/testResults.xml

